### ISSUE TITLE
Pokemon Trading Card Game API

### ISSUE THREAD

**Issue by Ahoward21** [Ahoward21/pokemon-search#2]
As a user I want to see be able to see the Pokemon trading card image when I search for a pokemon.

**Comment by nickperel** [comment]
When you search for a pokemon, it pulls up the base stats from the PokeAPI, and then it is fully connected to the PokeTCG API as well, which renders a high resolution image of the corresponding pokemon trading card from the pokemon name that was searched in the search bar. Functionality is fully working, so this issue is completed.
